### PR TITLE
Branch1

### PR DESCRIPTION
**Pull request by ZoroMak**

### CODE REVIEW

**Review by ZoroMak — COMMENTED** [review]
Молодец

**Comment by Arelav** [comment]
Am. What's going on here?

**Comment by kettanaito** [comment]
@Arelav, that, my friend, is a ban in the making.

**Comment by Arelav** [comment]
> @Arelav, that, my friend, is a ban in the making.

No problem. I just got about 3 emails today. Perhaps to learn git and GitHub a better option would be to do this no on the public repo.

**Pull request closed without merging**
