### PR TITLE
Replace shouldDisplayPagination with shouldPaginate

### LINKED ISSUE #6: Possible simplification of shouldDisplayPagination
Great summary. 

One question/suggestion - wouldn’t:

`const shouldDisplayPagination = (postsCount > 10) // alternatively`

be better as:

`const shouldPaginate = (postsCount > 10) // alternatively `

The latter is more concise and I think expresses the  meaning better(though I could have the meaning wrong).

### PR DESCRIPTION
**Pull request by donatoaguirre24**
#### 📄&nbsp; Description:

Simplify `shouldDisplayPagination` as @wflemingnz suggested.

---

#### ✔️&nbsp; Performed Tasks:

Replace `shouldDisplayPagination` with `shouldPaginate`

---

#### 📌&nbsp; Notes:

Fixes #6

### CODE REVIEW

**Comment by kettanaito** [comment]
This is a great suggestion, @donatoaguirre24! 

Could you please rebase on top of the latest master to solve the merge conflict? Please choose the `postCount` version of the code. Thanks.

**Comment by donatoaguirre24** [comment]
@kettanaito done 😁

**Comment by donatoaguirre24** [comment]
Hi @kettanaito, can we get this merged?

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
Thank you for this great addition, @donatoaguirre24 🎉

**Pull request merged**
